language: python

env:
  global:
    - R_VER=3.3.3
    - GGPLOT_VER=2.2.1

matrix:
    include:
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36

addons:
  apt:
    update: true
    packages:
    - libncurses5-dev
    - libncursesw5-dev
    - build-essential
    - pkg-config
    - zlib1g-dev
    - bzip2

install:
  - curl -fksSL https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 | tar xj
  - cd samtools-1.3.1 && ./configure --prefix=$PWD
  - make all all-htslib && make install install-htslib
  - export PATH=$PWD/bin:$PATH && cd -
  - export PATH=$PWD/ci:$PATH
  - docker build -t ci --build-arg R_VER --build-arg GGPLOT_VER -f ci/Dockerfile .
  - pip install tox

script:
  - tox
  - bash ci/run.sh
