language: python
os: linux
dist: focal
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
jobs:
  include:
  - stage: release
    env:
    - secure: Q51zmekFkaAc52qj4PJusD8ovl72rkrzCxNgD4SdYtJTpYesi/ZXDKD7bSjjZeV288nM4GGYdEz1DH1VhRm+6BltpdYa+Hx8niTZGR/scBUcO9O/99AlVokpVbaHZ45XbkpqshUjhHL3HN2jZvzoPC70vr5sWqNOOMm7d9DkBw89M+UGQ45t9aUVt2bswNmCHekApOowUw/3COJ1ILA04nIBX/fyqCRc86fQHp5ggbMDY67R5k9TJ8Id+NWyael5mcomCo9kJDgMzJRDdRYUqyTMqF7awqew1HUXCb19LKFJufM/m5Mewdkq43oM/lYzQtO/3X4Gjjzq1vqWPF80d+6mW55c38axZZv7KcnWCz2h52To+OQCvpQJdKxCcZFlegO26nDh/RNAaVhIP4dsQtQ8Bm6yzgocC2qgauBAXrLI+xR37GdqZF4LKcXxoTnZDOpRV84lb4gvbzWUQr+01sZvw1K0gkr/P3OTHeYTHDihXc0YmX/pB/99/gTwtgljTQ1abJwq7H9O8NaNUcO51szsAHsbCxkEgG4azL7RTCBO5ZYFGjZqUmpHI7D0xZlMAWjz3iOmJXeVBMNIIa99SO2EaQM3d7bmJ0LhtAhXii/AMkrj7ovnElhJEOUwDpvEKWZQi06NTSww8M0PlImrBEyp7o0uXsCoXNcUpuQiVhc=
    - secure: ojhMgfkXSgvdkBoaaE+AO0nMg91ccGtEoFiLSLZDxgbv0jaHmJk/VqFklpdlI9qfETK1vbScevkhoEWe8xK3F0asaX+IaQPa1qvFH4wz8oLdzFKZJ+dmUakr4F5jE1ezBwXI67N0Xdnr/JXc+TNcg1XLRjmtkd/mmV3WVzKVfmMPLY++N/CSbSEMQXd35LYGkpNqY3kZfNQEYljwSaatrNmmsGbIsFC26dAsJhlWnPRjURWT/4ixHosfeDWh+pI+rzQpM6n0IkjFkFW7ujj6kUQEyQ1RxgaXPtH3B3yIieuGy724MlAKhpogH2pgdSYJ3ku7j66VG5eWzJ6ymHUExX6MXo1w2cvtY23gCkOXy963l7bqXV6oUDiejKFsSIQt2MiUAl8mu2gm3R56iwAesSAKMhJXN0ryMOoonbErdVk1iYnB+SOfdZIf88pEulC7qE/644j+XgVGiem+hHSoBtnG1ZKaMhbKTzUXRscGaYWBtBLPR8J1corPLi4yrrGYTvBAwIjJFvUdlj7RWjfvhxvyxp5jVhUqiAouDE0kUzOITXNPAwaawk4QmpbgHKFrFCEdub4864M7TH7w0zqsU7UHjVuFufPYxfsHLVGJyO3Dr8Z9b8IZixfaDCMdtQZE6j3Zak+8+a7itikMTa+XLbNbHZTYRvZWUNPr5Skkl0k=
    - secure: sTAnnP6Bdvhbhz8223x8Zs85v5wyP47IgekX57vmFDRMziG/EG6IwlznlUMQp71i+ALDLtjsu7Y07/GbmIxUw4Xtjt7/EL78XnFqEtFeTHIeqetGtq1eRve/7ry+kIT7tJMN/V4qHwXhedFBZM6CGncl6b1J/IcrcN9ZrBBcydEUibK6uIROwoczkk7McWpd4zF9lrS8eue4YApXpPkSwTePUGtYHJS1E/ht2YeXTbR7utZo63KrB+Kf28OvRSU7odaZKRvyBQcCjv/6yetSaExAlerII7eoQVEBVbMP1/VTvaFKA7D/8XDRgjGjI/8bpMBbSQUpAVQMkroGZaCRYu6HMC83zYKNfQ4uoAhpQMYcP08FacQQ9zaKYq52BenPddHmMNoZ6Xuvtfc+dwIA66WnIMjAOv2Q7Uf5sy1loo/occKcvO7mwcmLFqVi54ccLlxBGBVkmSpccflJPRia6UVSCTa5caeBka1IKOZZlt/KwCzIculC3Mz7ShW2dw5UgImxTUl3nqDE219EusvIUgTdL3uRBaUYU91AjZEj766Ve5vO+2Nx2crUci44bJOyrodRsWJX1Qr0JuSCa/PgG9GLHQxMeqIO4+OH3h6+1y1o3wM1jqn/WapzYZzcWKrr0QjVsr5rX6O4pYUg9Gj1EKX0Hm55xCeFTkgbkpKs9zw=
    install:
    - go get github.com/github-release/github-release
    script:
    - bash ci/release.sh
    if: tag =~ ^v
env:
  global:
  - CONDA_PATH="$HOME/miniconda"
  - GGSASHIMI_ENV=test-env
  jobs:
  - R_VER=3.3.2 GGPLOT_VER=2.2.1
  - R_VER=3.6.3 GGPLOT_VER=3.3.3
  - R_VER=4.0.3 GGPLOT_VER=3.3.3
install:
- sudo apt update
- bash ci/setup-conda.sh
- pip install tox-travis
before_script:
- source "$CONDA_PATH/etc/profile.d/conda.sh"
- conda activate $GGSASHIMI_ENV
script:
- tox
- bash ci/run.sh
